FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS yes

RUN apt-get update && apt-get upgrade -y &&\
    # Install build tools, build dependencies and python
    apt-get install -y \
	python3-pip \
        build-essential \
        software-properties-common\
        cmake \
        git \
        wget \
        unzip \
        yasm \
        pkg-config \
        libcurl4-openssl-dev --fix-broken \
        libgmock-dev \
        libgtest-dev \
        libeigen3-dev \
        pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/ImageResize
